// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://catpqlpuwxdlzzkchvfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdHBxbHB1d3hkbHp6a2NodmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjIyODcsImV4cCI6MjA3MTQ5ODI4N30.uIgjwOsFofsG3iQRWs2S9pjxWxqwWRwOI1Dk7H4Fl2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});